version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: .
    command: npm -v
    links:
      - db
volumes:
  mysql-data:
    driver: local
